### ISSUE TITLE
Cards with States updating formatting

### ISSUE THREAD

**Issue by maddim12** [okviz/free-visuals#108] opened 2020-03-10 06:31 UTC
Since the update on March 9 the cards with states visual used in both Power Bi desktop and published Power Bi reports has changed formatting. This includes changing title/category locations and changing the formatting on the variance labels. 
Maddi

**Comment by danieleperilli** [comment] 2020-03-10 07:42
Can you provide a sample report?

**Comment by ChipDale66** [comment] 2020-03-10 11:55
we are experiencing issues with the background NOT going transparent when the condition is met

**Comment by danieleperilli** [comment] 2020-03-10 11:57
Please, we need some sample reports to fix these bugs.

**Comment by ChipDale66** [comment] 2020-03-10 12:00
notice you are rolling it back from 1.6.2 to 1.4.2
will try and create a test report but if you have rolled it back we won't be able to reproduce the issue

**Comment by ChipDale66** [comment] 2020-03-10 12:59
example report added
I think the issue for me is that the "No state color" has changed to white when it was originally set to no fill.
[example bug with card with states.zip](https://github.com/okviz/free-visuals/files/4312506/example.bug.with.card.with.states.zip)

**Comment by inserrv** [comment] 2020-03-10 14:34
I'm having this issue.  Please see image.  Card on left is Card with States. Card on right is built in Power BI card.  Out of no where time formatting issue became a problem on Card with States.  

![Capture](https://user-images.githubusercontent.com/62023150/76323085-99ae5680-62ba-11ea-83e4-ae2623df813a.PNG)

**Comment by danieleperilli** [comment] 2020-03-11 09:37
@inserrv Can you share your report? We are fixing each case and a sample file would be helpful. Thanks

**Comment by danieleperilli** [comment] 2020-03-11 09:42
@ChipDale66 In your case, you changed the forecolor of the label to get rid of an existing bug. In the latest version, we fixed that bug, but of course, this caused unexpected side effects on your report. Unfortunately, this will happens again when we release the fixed version in a few weeks.

**Comment by ChipDale66** [comment] 2020-03-11 11:37
Hi @danieleperilli what is the bug that is being fixed?

**Comment by danieleperilli** [comment] 2020-03-11 11:40
It should be https://github.com/okviz/free-visuals/issues/47

**Comment by inserrv** [comment] 2020-03-11 21:47
@danieleperilli.  I can't provide data as it's proprietary.  Also with the rolled back version, my dashboard is now working.  If you want to replicate my issue,  create a table with column Time with the values in seconds.  Create a measure that returns a time value that is the average of the time column.  ie Avg Time = time(0,0,average('Table'[Time]).  Format Avg Time in HH:MM:SS and then create a new Card with States containing the Avg Time value.  In ver 1.4.2 it would display correctly as a time value.  In ver 1.6.2 it was displaying as a full date and time, ignoring the formatting.

**Comment by ChipDale66** [comment] 2020-03-12 11:49
> @ChipDale66 In your case, you changed the forecolor of the label to get rid of an existing bug. In the latest version, we fixed that bug, but of course, this caused unexpected side effects on your report. Unfortunately, this will happens again when we release the fixed version in a few weeks.

thanks @danieleperilli how do we get notified that you are about to or have released the fixed  version? We will need to edit each report we use the visual on and reset the functionality, but would prefer to do this pro-actively rather than wait to find out because one of our users has reported that the reports are broken.

**Comment by danieleperilli** [comment] 2020-03-12 12:01
We will post a communication on our newsletter, then I will close this and the other issues.

**Comment by danieleperilli** [comment] 2020-03-12 12:01
@inserrv thanks for the repro steps!

**Closed** 2020-05-07 07:20 UTC
Labels: Card With States, fixed in beta/private
