### ISSUE TITLE
Bullet Chart - Tooltip position is not appropriate sometimes

### ISSUE THREAD

**Issue by rkhatua-aarete** [okviz/free-visuals#147] opened 2020-06-02 08:54 UTC
Hi Team,

The position of tooltip is sometimes at a top left corner of a report.

![Image 2](https://user-images.githubusercontent.com/63786998/83500721-c8645380-a4dc-11ea-99a8-18265ec8468a.jpg)

**Comment by okviz** [comment] 2020-06-02 08:59
Duplicate of #133

**Closed by okviz** 2020-06-02 08:59 UTC
Labels: Bullet Chart
