### ISSUE TITLE
Bullet Chart - X Axis Not Formatted Correctly

### ISSUE THREAD

**Issue by cbhoffm1** [okviz/free-visuals#78] opened 2019-11-18 20:21 UTC
The values in the X-Axis are showing periods (.) instead of commas (,).  I have checked the regional setting in both PBI Desktop and in the visual itself.  I have set both to English (United States) where the thousands separator should be a comma (,) not a period (.).
![Bullet Chart Formatting Issues 20191118](https://user-images.githubusercontent.com/47642807/69090864-604d9480-0a06-11ea-87e1-f4bbbbedb451.JPG)

**Comment by cbhoffm1** [comment] 2019-11-18 20:41
Attaching pbix with issue recreated
[OkVIz Bullet Chart Issues.zip](https://github.com/okviz/free-visuals/files/3860559/OkVIz.Bullet.Chart.Issues.zip)

**Comment by danieleperilli** [comment] 2019-11-19 06:23
The issue is not in the regional setting, but the space reserved for the axis element. Try to reduce the font size of the axis and the correct separator will appear. It will be fixed in the next version, thanks for reporting.

**Comment by danieleperilli** [comment] 2019-11-19 19:51
This has been fixed in v2.2.3. You can try the beta from this link: https://okviz.com/wp-content/okviz/pbiviz/free/bulletChartByOKViz.2.2.3-beta.pbiviz

**Comment by cbhoffm1** [comment] 2019-11-20 16:30
I uploaded the beta bullet chart into one of our dashboards and confirmed that the corrections are working.
Thanks

**Closed** 2019-12-23 04:13 UTC
Labels: Bullet Chart, bug, fixed in beta
