### ISSUE TITLE
Bullet Chart by OKviz - visual not showing in Internet Explorer

### ISSUE THREAD

**Issue by mamajoutt** [okviz/free-visuals#80] opened 2019-11-19 13:50 UTC
Hello everybody,

I need some urgent support pls. The bullet chart doesn't show in internet explorer, but it shows only in google chrome, firefox and MS edge..
Only IE is supported so the other browser is not an option :( Please provide a solution.

**Comment by danieleperilli** [comment] 2019-11-19 13:53
Duplicate of https://github.com/okviz/free-visuals/issues/79

**Closed by danieleperilli** 2019-11-19 13:53 UTC
