### ISSUE TITLE
Bullet Chart - not supporting converted currency values in the visual

### ISSUE THREAD

**Issue by sarumathiprince** [okviz/free-visuals#387] opened 2023-11-20 09:12 UTC
### Visual

Bullet Chart

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Bullet chart visual, we are trying to display currency values with the conversions. Example us dollars will show the value with dollar sign whereas currencies like INR, Canadian, Japanese will have their respective currency values based on their exchange rate conversions are done.

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.118.621.0 64-bit (June 2023)

### Sample report

n/a

### Screenshot

Dollar value is working fine..
<img width="345" alt="image" src="https://github.com/okviz/free-visuals/assets/151513643/56ecffe7-0c09-4139-95da-7a084af36ef9">

Other currency is not working.
<img width="341" alt="image" src="https://github.com/okviz/free-visuals/assets/151513643/666541cf-e0e3-408b-b0bb-f8022b9123fb">

**Comment by danieleperilli** [comment] 2023-11-20 09:14
Please provide a sample file.

**Comment by sarumathiprince** [comment] 2023-11-20 10:33
sample file attaching is not allowed from official machine.

**Comment by danieleperilli** [comment] 2023-11-22 06:14
It could be a duplicate of #388.
In any case the correct repo for reporting bugs on Bullet Chart is https://github.com/okviz/bullet-chart-issues/issues

**Closed by danieleperilli** 2023-11-22 06:14 UTC
Labels: bug, missing sample report, Bullet Chart
