### ISSUE TITLE
Card with States - Measures not displaying in Internet Explorer

### ISSUE THREAD

**Issue by jgerke01** [okviz/free-visuals#132] opened 2020-05-05 17:13 UTC
**Describe the issue**
This issue appears in the Power BI service. When opening a report that contains the Card with States visual using Internet Explorer, the measure is not display. The category appears, but the measure does not. This issue only occurs in Internet Explorer. It does not occur in Chrome or Microsoft Edge. 

**To Reproduce**
1. Publish a Power BI report to the Power BI server that uses the Card with States visual.
2. Open that Power BI report using Internet Explorer

**Expected behavior**
We expect the measure to be displayed. 

**Affected environment**
 - Power BI service

**REQUIRED: Repro file**
Error returned when trying to attach PBIX, email to follow.

***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
![Internet Explorer 5 5](https://user-images.githubusercontent.com/64856033/81094657-af09c080-8eb8-11ea-9662-fff3cabe32c6.png)
![Google Chrome 5 5](https://user-images.githubusercontent.com/64856033/81094666-b16c1a80-8eb8-11ea-97b3-5cf92e90f1b9.png)
![Microsoft Edge 5 5](https://user-images.githubusercontent.com/64856033/81094674-b3ce7480-8eb8-11ea-89e7-8c6933c3caf3.png)

**Comment by parthtanna** [comment] 2020-05-06 12:06
@danieleperilli Please take a look at this. The reference field displays, but the measure field does not appear in internet explorer. Seems to work on Chrome / edge just fine. 

Tested with clearing cache/cookies and tested with 1.6.3 and 1.6.5 versions.

**Comment by marcosqlbi** [comment] 2020-05-06 13:11
While we investigate the issue, you can downgrade to the previous version using the following instructions: https://okviz.com/blog/how-to-downgrade-a-visual-imported-from-the-appsource-marketplace/

**Comment by jgerke01** [comment] 2020-05-06 21:30
Thank you both for reviewing and following up. Do you have an idea yet as to what sort of timeline we are looking at (days/weeks/months)? That will give us a better sense as to how we should move forward.

Thank you for your help!

**Comment by marcosqlbi** [comment] 2020-05-07 06:06
Assuming we are able to reproduce the issue and fix it in the new version, if you need the visual deployed to the AppStore it takes at least 4-6 weeks to be certified and published by Microsoft. Therefore, in the short term you should use the procedure described in the link I posted in order to restore the previous version.

**Comment by danieleperilli** [comment] 2020-05-09 16:05
Can you confirm you see the issue yet? Because today it started working again for me. It could be a platform issue.

**Comment by jgerke01** [comment] 2020-05-12 21:00
We do still see issues with Internet Explorer. The visual is still working correctly in Chrome and Edge but does not work with Internet Explorer.

**Comment by parthtanna** [comment] 2020-05-12 22:59
I have not attempted a test yet. We are using the prior version until we test next or update from Jan 2020 PBIRS.

**Comment by danieleperilli** [comment] 2020-05-15 09:00
We isolated and fixed the issue. You can test a private version here: https://okviz.com/wp-content/okviz/pbiviz/free/cardWithStatesByOKViz-1.6.6-priv.pbiviz
Unfortunately, this version will unlikely reach the AppSource before 6 weeks due to another pending version in the approval pipeline.

**Comment by danieleperilli** [comment] 2020-05-15 09:01
Fixed in 1.6.6

**Closed by danieleperilli** 2020-05-15 09:00 UTC
Labels: Card With States, bug

**Comment by jgerke01** [comment] 2020-05-15 15:42
Glad to hear. Thank you for your help!
