### ISSUE TITLE
Bullet chart (free, long-time use on report) no longer depicting categories

### ISSUE THREAD

**Issue by LDittmann** [okviz/free-visuals#342] opened 2022-07-21 23:58 UTC
### Visual

Dot Plot

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use the OKViz Bullet Chart on a report that has made use of this visual for over 2 years.  Today we noticed that the categories we usually see do not appear to be coming through.   After (much) trial and error we confirmed all of the data is in the dataset, and comes through on other visuals, just not the OKViz bullet chart.  It appears we could create new versions of these visuals using the OKViz bullet chart (or other bullet charts) and reformat etc, but would prefer to just keep using our trusty old visual.  Any guidance on how to make that happen would help!

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

 2.106.582.0 64-bit (June 2022)

### Steps To Reproduce

1. Log into Power BI Service
2. Navigate to report that has been using the 

### Sample report

I cannot reproduce as the file is against a cube.  Even tried to convert to a direct query and then change to dummy data without success.

### Screenshot

![BulletChartFailure](https://user-images.githubusercontent.com/11587254/180330360-62ec3e6b-bd45-4e85-9189-53e5bfdc82de.PNG)
![Original BulletChart Version](https://user-images.githubusercontent.com/11587254/180333215-2c92f36e-7370-4b35-95c6-5e17206ac60e.PNG)

### Anything else?

please reach out if you have any questions - we have alot of reports subject to this issue.  Currently trying to use the older 2.2.8 version as 'the fix' but would like some validation that if it works, it will not be updated in the future

**Comment by dretamalesf** [comment] 2022-07-22 02:49
Hi, same issue in my reports now. Do you know how to use the older version in the reports?

**Comment by zhanglei592** [comment] 2022-07-22 03:04
> 

Hi there, you can download old version through this link, then import visual from file in PowerBI.
https://okviz.com/wp-content/okviz/pbiviz/free/bulletChartByOKViz-2.2.8-priv.pbiviz

**Comment by eriayala** [comment] 2022-07-22 03:16
Hi, same problem here. We've been using the visual for a couple of years and today it is not showing the categories properly.

**Comment by iverson3777** [comment] 2022-07-22 04:22
Hi there,
I found the cause of this issue may be the data label. After I swith off the data label, Category show up normally. Hope OKVIZ could fix this bug.
![image](https://user-images.githubusercontent.com/63550670/180361836-f4a11c1b-880c-4132-96f4-d35474edec8a.jpeg)
![image](https://user-images.githubusercontent.com/63550670/180361909-85aec38f-7597-4233-8643-ed65bfea4b9c.jpeg)

**Comment by danieleperilli** [comment] 2022-07-22 05:20
It has been fixed in v2.2.9.4. It will be available on Jul 27th.

Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.

**Closed by danieleperilli** 2022-07-22 05:20 UTC
Labels: bug, untriaged
