### ISSUE TITLE
Card with states - ie compatibility issues

### ISSUE THREAD

**Issue by luisacampos** [okviz/free-visuals#142] opened 2020-05-22 14:47 UTC
**Describe the issue**
The Card with states visualization is not showing the measure when the report is open through internet explorer. Works fine on Chrome.

**To reproduce**
Compare the reports on Chrome/ie

**Affected environment**
 - Power BI service

**REQUIRED: Repro file**
[sample.zip](https://github.com/okviz/free-visuals/files/4668745/sample.zip)

**Screenshots**
![Capture ie](https://user-images.githubusercontent.com/65774669/82679790-658bd600-9c19-11ea-934f-80b44af3dbd5.PNG)
![Capture chrome](https://user-images.githubusercontent.com/65774669/82679792-66246c80-9c19-11ea-97bc-29216f5c0755.PNG)

**Comment by danieleperilli** [comment] 2020-05-22 14:55
Duplicate of #139

**Closed by danieleperilli** 2020-05-22 14:55 UTC
Labels: Card With States

**Comment by luisacampos** [comment] 2020-05-22 15:08
Thank you very much
Ticket # 139 is saying that fix will be included in the next version v1.6.6, and the website says that version has been released on May 15th.  Do you know when the fix will be available on AppSource?

**Comment by danieleperilli** [comment] 2020-05-22 15:15
The release on our website is not synced with the version on the AppSource, because their approval process requires several weeks. Considering that there is yet another version in the approval pipeline (v1.6.5), the v1.6.6 will unlikely be in the AppSource before the end of June.
In the meantime, you can use the private version from our website, but it's not certified and doesn't update automatically like the version from the AppSource.

**Comment by luisacampos** [comment] 2020-05-22 15:48
Sounds good, Thank you!
