### ISSUE TITLE
Bullet Chart - Legend not showing default color

### ISSUE THREAD

**Issue by dedelman04** [okviz/free-visuals#96] opened 2020-01-15 19:04 UTC
Using the Bullet Chart with a Category, Value and 3 Targets (Threshold, Target, Maximum).

Using "Conditional Colors":
- if < Threshold, Red
- if < Target, Yellow
- if < Maximum, Orange
- Stop after first match

Set Default Color (under Data Colors) to Blue; "show all" is off.

On the Legend, the color for "Score" is the default PowerBI green (#01B8AA), not the default color set for the data (#007DC3).

See attached pbix (July 2019 release; 2.71.5523.941, 64-bit; Bullet Chart version says 2.2.2 but I downloaded 2.2.3 from the Microsoft Marketplace thru PowerBI)

[bullet.zip](https://github.com/okviz/free-visuals/files/4066916/bullet.zip)

Thanks
David Edelman

**Comment by danieleperilli** [comment] 2020-01-15 21:12
Duplicate of #77 - The new version is on its way to the marketplace.

**Closed by danieleperilli** 2020-01-15 21:12 UTC
Labels: Bullet Chart
